version: "3.9"
services: 
  mysql: 
    image: mysql:latest
    container_name: mysqldb
    restart: unless-stopped
    volumes: 
      - mysql-volume:/var/lib/mysql
    ports: 
      - 3306:3306
    environment: 
      MYSQL_DATABASE_FILE: /run/secrets/mysql_dbname
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_pass
      MYSQL_USER_FILE: /run/secrets/msql_user_name
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_user_pass
    secrets: 
      - db_root_password
      - db_password

secrets: 
  mysql_dbname: 
    file: secrets/mysql_dbname.secret 
  mysql_root_pass: 
    file: secrets/mysql_root_pass.secret 
  mysql_user_name: 
    file: secrets/mysql_user_name.secret 
  mysql_user_pass: 
    file: secrets/mysql_user_pass.secret

volumes: 
  mysql-volume: null
